spring:
  datasource:
    url: jdbc:h2:mem:priceapi;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: true
